### ISSUE TITLE
enable context for searches

### ISSUE THREAD

**Issue by craigsteffen** [ncsa/Nightingale_real#36]
I don't know what the differences are.  But when I search for something in Nightingale, all I get are a list of page titles that contain that phrase, but no other context.  

On Delta, I get the context (which I think is the default?).  

I don't remember ever setting something differently in the Nightingale repo, but if possible let's run down that (if it's a setting) and try to re-enable the context.  

Craig

**Comment by lhelms2** [comment]
@craigsteffen do you have an example search term? I tried 'anaconda' and it returned the context sentences it's included in. Maybe it also was just a glitch that worked itself out?
![Screenshot 2023-11-03 at 11 16 43 AM](https://github.com/ncsa/Nightingale_real/assets/141255627/b359d004-e63f-4770-9666-1749b7c3899a)

**Comment by craigsteffen** [comment]
I agree.  Whatever was happening isn't any more.  I'll close this.
