### ISSUE TITLE
SLURM commands only available on login nodes

### ISSUE THREAD

**Issue by pmenstrom** [ncsa/Nightingale_real#74]
Currently SLURM commands (such as sinfo, squeue, sbatch, etc) are not available on the group owned interactive nodes. They are only available on the login nodes.
I don't believe the "Running Jobs" section of the manual doesn't mention this.

Peter

**Comment by lhelms2** [comment]
@pmenstrom can you please provide a little more info about this. What should users with interactive nodes be doing as it relates to Slurm commands?

**Comment by pmenstrom** [comment]
@lhelms2 Not so much what users with interactive nodes need to do. All users with batch access need to submit from the login nodes. They cannot submit from any other nodes (compute, bastion host, project interactive nodes).

**Comment by lhelms2** [comment]
Craig submitted PR #75 for this.

**Comment by lhelms2** [comment]
PR #75 is merged into main.
