### ISSUE TITLE
scrontab

### ISSUE THREAD

**Issue by pmenstrom** [ncsa/Nightingale_real#76]
I have a note to document the scrontab command.
So far it has only been used by one user so it isn't high priority and may not really be necessary.

**Comment by lhelms2** [comment]
@pmenstrom what time zone are ``scrontab`` times in on Nightingale?

**Comment by pmenstrom** [comment]
The man page for scrontab says "The Slurm controller's timezone is what will be used to evaluate each crontab's repetition intervals. User-specific timezones are not supported."

**Comment by lhelms2** [comment]
As I understand it, that means that Slurm on Nightingale has a set time zone, I don't know what that is (UTC, Central, something else?). 
(Instead of ``scrontab`` using whatever time zone a particular user happens to be in.)

**Comment by pmenstrom** [comment]
Benjamin says Central time zone.

**Comment by lhelms2** [comment]
PR #83 submitted for review/approval

**Comment by lhelms2** [comment]
PR is merged into main
